# Generated by Django 4.0.5 on 2022-06-12 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BastauApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id_student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BastauApp.student', verbose_name='Студент'),
        ),
    ]
